name: Heads Compat Matrix

env:
  K_SOUP_COV_DO: false

on:
  push:
    branches:
      - 'main'
    tags:
      - '!*' # Do not execute on tags
  pull_request:
    branches:
      - '*'
  # Allow manually triggering the workflow.
  workflow_dispatch:

permissions:
  contents: read

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    name: Specs - Ruby ${{ matrix.ruby }} ${{ matrix.appraisal }}${{ matrix.name_extra || '' }}
    if: "!contains(github.event.commits[0].message, '[ci skip]') && !contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || endsWith(matrix.ruby, 'head') }}
    env: # $BUNDLE_GEMFILE must be set at job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}.gemfile
    strategy:
      fail-fast: true
      matrix:
        include:
          # ruby-head
          - ruby: "ruby-head"
            appraisal: "ruby-head"
            exec_cmd: "turbo_tests -n4"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # truffleruby-head
          - ruby: "truffleruby-head"
            appraisal: "truffleruby-head"
            exec_cmd: "turbo_tests -n4"
            gemfile: "Appraisal.root"
            rubygems: latest
            bundler: latest

          # jruby-head
          # Error output has a significantly different format in JRuby :(
          #  - ruby: "jruby-head"
          #    appraisal: "jruby-head"
          #    exec_cmd: "turbo_tests -n4"
          #    gemfile: "Appraisal.root"
          #    rubygems: latest
          #    bundler: latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby & RubyGems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: ${{ matrix.rubygems }}
          bundler: ${{ matrix.bundler }}
          bundler-cache: false

      # Raw `bundle` will use the BUNDLE_GEMFILE set to matrix.gemfile (i.e. Appraisal.root)
      # We need to do this first to get appraisal installed.
      # NOTE: This does not use the main Gemfile at all.
      - name: Bundle install for Appraisal ${{ matrix.appraisal }}
        run: bundle
      - name: Install Appraisal ${{ matrix.appraisal }} dependencies
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle
      - name: Run ${{ matrix.appraisal }} tests via ${{ matrix.exec_cmd }}
        run: bundle exec appraisal ${{ matrix.appraisal }} bundle exec ${{ matrix.exec_cmd }}
